wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1652783854
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.16
      8:
      - 4
      - 5
architecture:
  desc: null
  value: LSTM
batch_size:
  desc: null
  value: 60
dataset:
  desc: null
  value: Actor_1_Bed
dropout:
  desc: null
  value: 0.8
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.01
loss_function:
  desc: null
  value: sparse_categorical_crossentropy
lstm1_units:
  desc: null
  value: 32
model:
  desc: null
  value: LSTM
num_features:
  desc: null
  value: 2048
sequence_length:
  desc: null
  value: 20
sliding_window_stride:
  desc: null
  value: 10
split_ratio:
  desc: null
  value: 0.7
